#ifndef CONFIGURATION_H
#define CONFIGURATION_H

#define VEHICLE_TYPE_AIRBOAT

#define WIFI_SSID "AutisticDrones"
#define WIFI_PASSWORD "Autyzm2137"
#define UDP_CONTROLL_PORT 4210
#define MAX_ROGUE_TIME 1000
#define MIN_RSSI -80
#define COMMUNICATION_METHOD 3
#define TELEMETRY_TIME 1000

enum DroneStatus
{
    WORKS,
    WARNING,
    BROKEN
};

#define USE_WIREGUARD 0

#if USE_WIREGUARD
    #define WG_LOCAL_IP "10.0.0.2"
    #define WG_PRIVATE_KEY "KLUCZ_PRYWATNY_ESP32="
    #define WG_PEER_ADDRESS "198.51.100.1"
    #define WG_PEER_PORT 51820
    #define WG_PEER_PUBLIC_KEY "KLUCZ_PUBLICZNY_SERWERA="
#endif

#endif